// <auto-generated />
using System;
using MVP_Monitoring.Infra.Data.Common.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVP_Monitoring.Infra.Data.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20240626063502_DeviceLogo")]
    partial class DeviceLogo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVP_Monitoring.Domain.Entities.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseTblDevices", (string)null);
                });

            modelBuilder.Entity("MVP_Monitoring.Domain.Entities.DeviceItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("BaseTblDeviceItems", (string)null);
                });

            modelBuilder.Entity("MVP_Monitoring.Domain.Entities.DeviceItemParametersValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BearingTemperature")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DeviceItemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MotorFlow")
                        .HasColumnType("int");

                    b.Property<int>("RotationSpeed")
                        .HasColumnType("int");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceItemId");

                    b.ToTable("BaseTblDeviceItemParametersValues", (string)null);
                });

            modelBuilder.Entity("MVP_Monitoring.Domain.Entities.DeviceItem", b =>
                {
                    b.HasOne("MVP_Monitoring.Domain.Entities.Device", "Device")
                        .WithMany("DeviceItems")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MVP_Monitoring.Domain.Entities.DeviceItemParametersValue", b =>
                {
                    b.HasOne("MVP_Monitoring.Domain.Entities.DeviceItem", "DeviceItem")
                        .WithMany("deviceItemParametersValues")
                        .HasForeignKey("DeviceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceItem");
                });

            modelBuilder.Entity("MVP_Monitoring.Domain.Entities.Device", b =>
                {
                    b.Navigation("DeviceItems");
                });

            modelBuilder.Entity("MVP_Monitoring.Domain.Entities.DeviceItem", b =>
                {
                    b.Navigation("deviceItemParametersValues");
                });
#pragma warning restore 612, 618
        }
    }
}
